[2023-12-06T21:49:08.313+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag2.download_data scheduled__2023-01-12T00:00:00+00:00 [queued]>
[2023-12-06T21:49:08.321+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag2.download_data scheduled__2023-01-12T00:00:00+00:00 [queued]>
[2023-12-06T21:49:08.321+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-06T21:49:08.444+0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_data> on 2023-01-12 00:00:00+00:00
[2023-12-06T21:49:08.448+0500] {standard_task_runner.py:57} INFO - Started process 8602 to run task
[2023-12-06T21:49:08.452+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag2', 'download_data', 'scheduled__2023-01-12T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/airflow_dag.py', '--cfg-path', '/tmp/tmpi87s_at7']
[2023-12-06T21:49:08.453+0500] {standard_task_runner.py:85} INFO - Job 26: Subtask download_data
[2023-12-06T21:49:08.579+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_dag2.download_data scheduled__2023-01-12T00:00:00+00:00 [running]> on host amina-HP-ProBook-450-G2
[2023-12-06T21:49:08.806+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='amina_bibi' AIRFLOW_CTX_DAG_ID='etl_dag2' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-12T00:00:00+00:00'
[2023-12-06T21:49:12.628+0500] {logging_mixin.py:154} INFO - Access denied with the following error:
[2023-12-06T21:49:12.628+0500] {logging_mixin.py:154} WARNING -  	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 
[2023-12-06T21:49:12.629+0500] {logging_mixin.py:154} WARNING - You may still be able to access the file from the browser:
[2023-12-06T21:49:12.629+0500] {logging_mixin.py:154} WARNING - 
	 https://drive.google.com/uc?id=10iZbAEEw7t8rtaD39OiuE9qPB8eSF3OJ 
[2023-12-06T21:49:12.629+0500] {python.py:194} INFO - Done. Returned value was: None
[2023-12-06T21:49:12.638+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dag2, task_id=download_data, execution_date=20230112T000000, start_date=20231206T164908, end_date=20231206T164912
[2023-12-06T21:49:12.762+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-06T21:49:12.788+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
